name: Trigger Remote Workflow on Release

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag'
        required: true
        type: string

jobs:
  trigger-remote-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Extract release tag
        id: extract_tag
        run: echo "RELEASE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Trigger remote workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: Cliffback/FlashGBX-macOS
          event-type: workflow-dispatch
          client-payload: '{"create_release": true, "latest_version": "${{ env.RELEASE_TAG }}"}'
  trigger-v1:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Remote Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Build FlashGBX Remotely
          token: ${{ secrets.PAT }}
          repo: Cliffback/FlashGBX-macOS
          inputs: '{"create_release": "true", "latest_version": "${{ github.event.release.tag_name }}"}'
  trigger-v2:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Remote Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Build FlashGBX Remotely
          token: ${{ secrets.PAT }}
          repo: Cliffback/FlashGBX-macOS
          inputs: '{"create_release": "true", "latest_version": "1.1"}'
